version: "3.9" # optional since v1.27.0
services:
  server:
    build: ./server
    volumes:
      - "./server:/server"
    ports:
      - "3000:3000"
      - "20777:20777/udp"
  app:
    build: ./app
    volumes:
      - "./app:/app"
    ports:
      - "80:3000"
